# Generated by Django 3.0 on 2020-01-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='user',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='username',
            field=models.CharField(default='NULL', max_length=100),
            preserve_default=False,
        ),
    ]
