# Generated by Django 3.0 on 2020-01-24 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_topic'),
        ('users', '0002_auto_20200125_0215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='TopicsFollowing',
        ),
    ]
