# Generated by Django 3.0 on 2020-01-24 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_creator_topics'),
        ('users', '0003_auto_20200125_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorsFollowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('creator_following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Creator')),
            ],
        ),
    ]
