# Generated by Django 3.0 on 2020-01-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='username',
        ),
    ]
