# Generated by Django 3.0 on 2020-01-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='topics',
            field=models.ManyToManyField(to='content.Topic'),
        ),
    ]
